version: "3"

dotenv:
  - .env

includes:
  mig:
    taskfile: ./infrastructure/migrations/Taskfile.yaml
    dir: ./
  pg:
    taskfile: ./.scripts/Taskfile.yaml
    dir: ./
    vars:
      PROJECT_DIR: "{{.TASKFILE_DIR}}"

tasks:
  default:
    desc: "🖥️ Run the application in local mode (Actually runs the `task local`)."
    deps: ["local"]

  run:
    desc: "🖥️ Run the bootstrap application."
    cmds:
      - cargo run

  check:
    desc: "🔎 Run cargo check for the whole workspace."
    cmds:
      - cargo check --workspace
      - cargo clippy --workspace --all-targets -- -D warnings

  test:
    desc: "🧪 Run all workspace tests."
    cmds:
      - cargo test --workspace

  fmt:
    desc: "🧹 Format the whole workspace."
    cmds:
      - cargo fmt --all

  pre:
    desc: "🛡️ Run pre-commit checks."
    deps: ["fmt", "check", "test"]

  pipeline:
    desc: "🚀 Clear terminal, format, test, build and run in release mode."
    cmds:
      - task: pre
      - cargo build --workspace
      - cargo run --release

  local:
    desc: "🖥️ Run the application in local mode."
    deps: ["pre"]
    cmds:
      - echo "Starting local development server at http:/http://127.0.0.1:{{.SERVER_PORT}}/docs/ 🚀"
      - task: run

  entity:
    desc: "🔄 Regenerate SeaORM entities from the database."
    vars:
      DATABASE_URL: "postgres://{{.POSTGRES_USER}}:{{.POSTGRES_PASSWORD}}@{{.POSTGRES_HOST}}:{{.POSTGRES_PORT}}/{{.POSTGRES_DB}}"
    cmds:
      - sea-orm-cli generate entity
        -u "{{.DATABASE_URL}}"
        -o infrastructure/src/adapters/persistence/seaorm/entities
        --ignore-tables migrations
        --database-schema "{{.POSTGRES_SCHEMA}}"
