### Create new user.
# @name Register user
POST http://{{SERVER_HOST}}:{{SERVER_PORT}}/v1/auth/register/
Accept: application/json
Content-Type: application/json

{
  "email": "kostiantyn.salnykov@gmail.com",
  "phone": "+380978531216",
  "password": "Fake123 password",
  "first_name": "Kostiantyn",
  "last_name": "Salnykov"
}

>>! {{$projectRoot}}/api_client/response/auth/register.json


### Login.
# @name Login user
POST http://{{SERVER_HOST}}:{{SERVER_PORT}}/v1/auth/login/
Accept: application/json
Content-Type: application/json

{
  "email": "kostiantyn.salnykov@gmail.com",
  "password": "Fake123 password"
}

> {%
  client.global.set("access_token", response.body.data.access_token);
  client.global.set("refresh_token", response.body.data.refresh_token);
  client.global.set("user_id", response.body.data.user_id);
  %}

>>! {{$projectRoot}}/api_client/response/auth/login.json



### Refersh token to new pair.
# @name Refersh token to new pair.
POST http://{{SERVER_HOST}}:{{SERVER_PORT}}/v1/auth/token/refresh/
Accept: application/json
Content-Type: application/json

{
  "refresh_token": "{{refresh_token}}"
}

>>! {{$projectRoot}}/api_client/response/auth/token/refresh.json