GET http://{{SERVER_HOST}}:{{SERVER_PORT}}/health_check/
Accept: application/json

###

POST http://{{SERVER_HOST}}:{{SERVER_PORT}}/users/register/
Accept: application/json
Content-Type: application/json

{
  "email": "new.user@example.com",
  "password": "supersecret123",
  "first_name": "New",
  "last_name": "User"
}


###

POST http://{{SERVER_HOST}}:{{SERVER_PORT}}/users/register/
Accept: application/json
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "12345678",
  "first_name": null,
  "last_name": null
}