### Users me.
# @name Get user from access_token
GET http://{{SERVER_HOST}}:{{SERVER_PORT}}/v1/users/me/
Accept: application/json
Authorization: Bearer {{access_token}}

>>! {{$projectRoot}}/api_client/response/users/me.json