//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19
#![allow(unused_imports)]

pub use super::users::Entity as Users;
pub use super::users_wishlists::Entity as UsersWishlists;
pub use super::wishlists::Entity as Wishlists;
