//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "auth_provider")]
pub enum AuthProvider {
    #[sea_orm(string_value = "google")]
    Google,
    #[sea_orm(string_value = "meta")]
    Meta,
    #[sea_orm(string_value = "github")]
    Github,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "users_status")]
pub enum UsersStatus {
    #[sea_orm(string_value = "unconfirmed")]
    Unconfirmed,
    #[sea_orm(string_value = "confirmed")]
    Confirmed,
    #[sea_orm(string_value = "force_change_password")]
    ForceChangePassword,
    #[sea_orm(string_value = "waiting_for_deletion")]
    WaitingForDeletion,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "users_wishlists_role"
)]
pub enum UsersWishlistsRole {
    #[sea_orm(string_value = "owner")]
    Owner,
    #[sea_orm(string_value = "reader")]
    Reader,
    #[sea_orm(string_value = "writer")]
    Writer,
}
