//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::AuthProvider;
use super::sea_orm_active_enums::UsersStatus;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub first_name: String,
    pub last_name: String,
    #[sea_orm(unique)]
    pub email: String,
    #[sea_orm(unique)]
    pub phone: Option<String>,
    pub password_hash: Option<String>,
    pub status: UsersStatus,
    pub provider: Option<AuthProvider>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub settings: Option<Json>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::users_wishlists::Entity")]
    UsersWishlists,
}

impl Related<super::users_wishlists::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UsersWishlists.def()
    }
}

impl Related<super::wishlists::Entity> for Entity {
    fn to() -> RelationDef {
        super::users_wishlists::Relation::Wishlists.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::users_wishlists::Relation::Users.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
